PF_FIX_SLOPE_NW_RAF = FDNS = 0
PF_FULL_NW_RAF = FNSL = 1
PF_DEC_NW_RAF = NSOL = 2
PF_GAUSS_SDL = SOLV = 3
PF_MOD_GAUSS_SDL = MSLV =4

TAP_LOCK = 0
TAP_STEPPING = 1
TAP_DIRECT = 2

TAP = {'LOCK':0, 'STEPPING':1, 'DIRECT':2}
TAPS = ['LOCK', 'STEPPING', 'DIRECT']

SW_SHANT_LOCK = 0
SW_SHANT_ENABLE_ALL = 1
SW_SHANT_CONTINUOUS = 2

AR_INTR_DISABLED = 0
AR_INTR_TIELINE = 1
AR_INTR_TIELINE_LD = 2

SCALE_P_OFF = 0
SCALE_P_TOTAL = 1
SCALE_P_PERCENT = 2
SCALE_P_INC = 3

SCALE_Q_OFF = 0
SCALE_Q_CONST = 1
SCALE_Q_TOTAL = 2
SCALE_Q_PERCENT = 3
SCALE_Q_POW_FACT = 4
SCALE_Q_INC = 5

SCALE_BUS_TYPE_1 = 0
SCALE_BUS_TYPE_2_3 = 1
SCALE_BUS_TYPE_ALL = 2



